/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Mariana M
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPricipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnu_cliente = new javax.swing.JMenu();
        registrocliente = new javax.swing.JMenuItem();
        editarcliente = new javax.swing.JMenuItem();
        mnu_mascota = new javax.swing.JMenu();
        mnu_vetrinario = new javax.swing.JMenu();
        registrarveterinario = new javax.swing.JMenuItem();
        mnu_vendedor = new javax.swing.JMenu();
        mnu_historiaclinica = new javax.swing.JMenu();
        mnu_factura = new javax.swing.JMenu();
        mnu_acercade = new javax.swing.JMenu();
        mnu_salir1 = new javax.swing.JMenu();
        cerrarsesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Principal");

        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        mnu_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        mnu_cliente.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconcliente.png")); // NOI18N
        mnu_cliente.setText("Clientes");

        registrocliente.setText("Registrar nuevo cliente");
        registrocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroclienteActionPerformed(evt);
            }
        });
        mnu_cliente.add(registrocliente);

        editarcliente.setText("Editar");
        editarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarclienteActionPerformed(evt);
            }
        });
        mnu_cliente.add(editarcliente);

        jMenuBar2.add(mnu_cliente);

        mnu_mascota.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconMascotas.png")); // NOI18N
        mnu_mascota.setText("Mascotas");
        jMenuBar2.add(mnu_mascota);

        mnu_vetrinario.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconveterinario.png")); // NOI18N
        mnu_vetrinario.setText("Veterinarios");

        registrarveterinario.setText("Registrar Veterinario");
        registrarveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarveterinarioActionPerformed(evt);
            }
        });
        mnu_vetrinario.add(registrarveterinario);

        jMenuBar2.add(mnu_vetrinario);

        mnu_vendedor.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconvendedor.png")); // NOI18N
        mnu_vendedor.setText("Vendedores");
        jMenuBar2.add(mnu_vendedor);

        mnu_historiaclinica.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconhistoriaclinica.png")); // NOI18N
        mnu_historiaclinica.setText("Historias Clínicas");
        jMenuBar2.add(mnu_historiaclinica);

        mnu_factura.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconfactura.png")); // NOI18N
        mnu_factura.setText("Facturas");
        jMenuBar2.add(mnu_factura);

        mnu_acercade.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\iconacerca-de.png")); // NOI18N
        mnu_acercade.setText("A cerca de nosotros");
        jMenuBar2.add(mnu_acercade);

        mnu_salir1.setIcon(new javax.swing.ImageIcon("E:\\USUARIO\\Escritorio\\Mariana Montoya\\INGENIERÍA INFORMÁTICA\\SEMESTRE IV\\TALLER DE PROGRAMACIÓN\\ProyectoVeterinaria\\src\\main\\java\\Vista\\images\\salida.png")); // NOI18N
        mnu_salir1.setText("Salir");

        cerrarsesion.setText("Cerrar sesión");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        mnu_salir1.add(cerrarsesion);

        jMenuBar2.add(mnu_salir1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroclienteActionPerformed

    private void editarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarclienteActionPerformed

    private void registrarveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarveterinarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_registrarveterinarioActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarsesion;
    private javax.swing.JMenuItem editarcliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnu_acercade;
    private javax.swing.JMenu mnu_cliente;
    private javax.swing.JMenu mnu_factura;
    private javax.swing.JMenu mnu_historiaclinica;
    private javax.swing.JMenu mnu_mascota;
    private javax.swing.JMenu mnu_salir1;
    private javax.swing.JMenu mnu_vendedor;
    private javax.swing.JMenu mnu_vetrinario;
    private javax.swing.JMenuItem registrarveterinario;
    private javax.swing.JMenuItem registrocliente;
    // End of variables declaration//GEN-END:variables

    
    
    public JMenuItem getEditarcliente() {
        return editarcliente;
    }

    public void setEditarcliente(JMenuItem editarcliente) {
        this.editarcliente = editarcliente;
    }

    public JMenu getMnu_acercade() {
        return mnu_acercade;
    }

    public JMenu getMnu_cliente() {
        return mnu_cliente;
    }

    public void setMnu_cliente(JMenu mnu_cliente) {
        this.mnu_cliente = mnu_cliente;
    }

    public JMenu getMnu_factura() {
        return mnu_factura;
    }

    public void setMnu_factura(JMenu mnu_factura) {
        this.mnu_factura = mnu_factura;
    }

    public void setMnu_acercade(JMenu mnu_acercade) {
        this.mnu_acercade = mnu_acercade;
    }

    public void setMnu_historiaclinica(JMenu mnu_historiaclinica) {
        this.mnu_historiaclinica = mnu_historiaclinica;
    }

    public JMenu getMnu_mascota() {
        return mnu_mascota;
    }

    public void setMnu_mascota(JMenu mnu_mascota) {
        this.mnu_mascota = mnu_mascota;
    }

    public JMenu getMnu_salir1() {
        return mnu_salir1;
    }

    public void setMnu_salir1(JMenu mnu_salir1) {
        this.mnu_salir1 = mnu_salir1;
    }

    public JMenu getMnu_vendedor() {
        return mnu_vendedor;
    }

    public void setMnu_vendedor(JMenu mnu_vendedor) {
        this.mnu_vendedor = mnu_vendedor;
    }

    public JMenu getMnu_vetrinario() {
        return mnu_vetrinario;
    }

    public void setMnu_vetrinario(JMenu mnu_vetrinario) {
        this.mnu_vetrinario = mnu_vetrinario;
    }

    public JMenuItem getRegistrocliente() {
        return registrocliente;
    }

    public void setRegistrocliente(JMenuItem registrocliente) {
        this.registrocliente = registrocliente;
    }

    public JMenuItem getRegistrarveterinario() {
        return registrarveterinario;
    }

    public JMenuItem getCerrarsesion() {
        return cerrarsesion;
    }

}
